language: node_js
node_js:
- '12.13'

script:
  - git stash clear # WTF travis?!
  - npm test

deploy:
  provider: npm
  email: emiliano.heyns@iris-advies.com
  on:
    tags: true
  api_key:
    secure: CE5AGTK61kCFlCEIn4gbDxxEHbfhc9pinyAVWnUItdAG9w3puSy4rkq5V1op/cs6Uw7n2xHrs7DQ7ofRJtTdK+d3FpiBdjB8E0s4e7nban++eGoedUyvpm0sQOOEOcsNOMJDdYyoQ5Vxj9BK6wCFVJZWTKmY88lWP154wuzw2zmFa8lAtQmynoOTRFIInQr6TW6eqeb2or8Kn39ezfGT1OOU+xy70mLzAFzABpSjkz5QlvucxbkiZ3wCV5L9jQ8PM2/JLpP4hR3oYmfbDfHGCxHBj/1jCvjMDT14qGvF7XxQap0cd7lAYZR6NlpAhMyth9x6cY6tjK8rOAbjvqhBIY4y43fr0iuNM1TqGVwOJvQ5K0wg0jN24bZk4ts+qG9SPBAUbAuQB/XqObW5xGazYV/4ItbdrP/DlVK7YKiT7biGbS43FQigh5QygYcygxDgC2N+/O7cnSn4YoqraUzQH9facYegAqQDfaS3+nmVWMWHW77/o3DWH8ASt+BKzUJ8ej9i1xr8crmeVFa2VMM/nJoiIrj1s1AHt8YEbBHaiT3aYcqXFAgN2tRBpG+oK5SupBSQvOfFMBsUQmhE3lfno5lYqclnD9QWkDI7VmZ1BBaY2DOnbY4Z3nB2oHxHI3cobR1f6YZHjTW0gwUtrnAzpJmc6dqUBQW5X8PcxfifwUY=
